#pragma once
#ifndef PCH_H
#define PCH_H
#define _SILENCE_STDEXT_ALLOCATORS_DEPRECATION_WARNING
#include <vector>
#include <QMainWindow>
#include <cmath>
#include <memory_resource>
#include <stack>
#include <map>
#include <QPushButton>
#include <QGraphicsView>
#include <functional>
#include <cassert>
#endif PCH_H
